server:
  port: 8081
  servlet:
    context-path: /app
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude:
      exclude: WEB-INF/**

defuserInfo:
  name: zhengjirui
  nick: jirui
  age: 25
  sex: nan
  address: "${defuserInfo.name}"